[workspace]
resolver = "2"
members = [
  "bridge",
  "vrrop_client",
]

[workspace.dependencies]
anyhow = "1"
packed_struct = "0.10"
cobs = "0.2.3"
thiserror = "1.0"
crc = "3.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
